# Generated by Django 6.0.4 on 2026-05-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_traineraccountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineraccountrequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
