# Generated by Django 6.0.4 on 2026-05-23 02:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_move_student_models_to_student_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsmis', models.CharField(blank=True, max_length=32)),
                ('uli', models.CharField(blank=True, max_length=64)),
                ('entry_date', models.DateField()),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('name_extension', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (11 digits, starting with 09).', regex='^09\\d{9}$')])),
                ('region_code', models.CharField(max_length=32)),
                ('province_code', models.CharField(max_length=32)),
                ('city_code', models.CharField(max_length=32)),
                ('barangay_code', models.CharField(max_length=32)),
                ('nationality', models.CharField(default='Filipino', max_length=64)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=16)),
                ('employment_status', models.CharField(blank=True, max_length=32)),
                ('birth_date', models.DateField()),
                ('birthplace', models.CharField(blank=True, max_length=255)),
                ('educational_attainment', models.CharField(blank=True, max_length=128)),
                ('parent_guardian_name', models.CharField(blank=True, max_length=150)),
                ('parent_guardian_address', models.CharField(blank=True, max_length=255)),
                ('client_classifications', models.JSONField(blank=True, default=list)),
                ('selected_program', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('training_with_assessment', 'Training with Assessment'), ('assessment_only', 'Assessment Only')], max_length=40)),
                ('scholarship_type', models.CharField(blank=True, max_length=32)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=255)),
                ('photo', models.FileField(blank=True, upload_to='students/enrollment_photos/%Y/%m/')),
                ('profile_step_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tesda_profile', to='student.studentregistration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student enrollment profile',
                'verbose_name_plural': 'Student enrollment profiles',
                'db_table': 'student_enrollmentprofile',
            },
        ),
    ]
