# Generated by Django 6.0.4 on 2026-05-23 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_enrollment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='contact_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number.', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='emergency_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number.', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number.', regex='^09\\d{9}$')]),
        ),
    ]
