# Generated by Django 6.0.4 on 2026-05-23 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentenrollmentprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollmentprofile',
            name='requirements_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentenrollmentprofile',
            name='requirements_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentEnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('valid_id', 'Valid ID'), ('photo_2x2', '2x2 Photo'), ('good_moral', 'Certificate of Good Moral'), ('transcript', 'Transcript of Records')], max_length=32)),
                ('file', models.FileField(upload_to='students/enrollment_documents/%Y/%m/')),
                ('id_type', models.CharField(blank=True, max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student.studentenrollmentprofile')),
            ],
            options={
                'db_table': 'student_enrollmentdocument',
                'ordering': ['document_type'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'document_type'), name='unique_profile_document_type')],
            },
        ),
    ]
