# Generated by Django 6.0.4 on 2026-05-24 14:12

import backend.student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_disability_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to=backend.student.models.enrollment_photo_upload_to),
        ),
    ]
