# Generated by Django 6.0.4 on 2026-06-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studentregistration_egace_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='egace_certificate',
            field=models.BooleanField(default=False, help_text='Deprecated — certificate is derived from trainer grades (graduate + assessment).'),
        ),
    ]
