# Generated by Django 6.0.4 on 2026-07-22 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_studentregistration_egace_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='barangay_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='city_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number.', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='privacy_consent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='profile_step_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='program_type',
            field=models.CharField(blank=True, choices=[('training_with_assessment', 'Training with Assessment'), ('assessment_only', 'Assessment Only')], max_length=40),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='province_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='region_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='selected_program',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentenrollmentprofile',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
