# Generated by Django 6.0.4 on 2026-10-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_studentdocumentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocumentrequest',
            name='release_date',
            field=models.DateField(blank=True, help_text='Date when student can pick up / get the document', null=True),
        ),
    ]
