# Generated by Django 6.0.4 on 2026-05-25 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0013_document_registrar_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(db_index=True, max_length=32)),
                ('or_number', models.CharField(blank=True, max_length=64)),
                ('receipt_type', models.CharField(choices=[('OR', 'Invoice'), ('AR', 'Acknowledgement Receipt')], default='OR', max_length=8)),
                ('student_name', models.CharField(max_length=255)),
                ('particulars', models.JSONField(default=list)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], default='Unpaid', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_payments', to='student.studentenrollmentprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_payments', to='student.studentregistration')),
            ],
            options={
                'db_table': 'cashier_payment',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('control_number',), name='cashier_payment_control_number_unique')],
            },
        ),
    ]
