# Generated by Django 6.0.4 on 2026-07-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_alter_registrarscheduletemplate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarscheduletemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
