# Generated by Django 6.0.4 on 2026-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_registrarscheduletemplate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarscheduletemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], db_index=True, default='draft', max_length=16),
        ),
    ]
