# Generated by Django 6.0.4 on 2026-10-04 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_alter_registrarscheduletemplate_status'),
        ('student', '0019_studentdocumentrequest_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipGrantBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=200)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('total_parsed_rows', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registrar_scholarshipgrantbatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarGrantRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scholar_name', models.CharField(max_length=200)),
                ('sponsor_name', models.CharField(max_length=200)),
                ('slot_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.CharField(blank=True, max_length=64)),
                ('scholarship_type', models.CharField(default='tesda', max_length=32)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_grants', to='student.studentenrollmentprofile')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_grants', to='student.studentregistration')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_records', to='registrar.scholarshipgrantbatch')),
            ],
            options={
                'db_table': 'registrar_scholargrantrecord',
                'ordering': ['-granted_at'],
            },
        ),
    ]
