# Generated by Django 6.0.4 on 2026-10-04 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0008_scholarshipgrantbatch_scholargrantrecord'),
        ('student', '0019_studentdocumentrequest_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholargrantrecord',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_grants', to='student.studentregistration'),
        ),
    ]
