# Generated by Django 6.0.4 on 2026-10-04 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0009_alter_scholargrantrecord_registration'),
        ('student', '0019_studentdocumentrequest_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholargrantrecord',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholargrantrecord',
            name='birthdate',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scholargrantrecord',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='scholargrantrecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scholargrantrecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scholargrantrecord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scholargrantrecord',
            name='no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scholargrantrecord',
            name='program',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scholargrantrecord',
            name='amount',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='scholargrantrecord',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_grants', to='student.studentenrollmentprofile'),
        ),
        migrations.AlterField(
            model_name='scholargrantrecord',
            name='scholar_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scholargrantrecord',
            name='scholarship_type',
            field=models.CharField(blank=True, default='tesda', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='scholargrantrecord',
            name='slot_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='scholargrantrecord',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
