# Generated by Django 6.0.4 on 2026-05-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portalnotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='core_portal_user_id_1563c6_idx',
            old_name='core_portal_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='core_portal_user_id_9e5dd6_idx',
            old_name='core_portal_user_id_read_idx',
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='category',
            field=models.CharField(choices=[('enrollment_requirements', 'Enrollment requirements'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('documents_released', 'Documents released'), ('payment_received', 'Payment received'), ('general', 'General')], db_index=True, default='general', max_length=32),
        ),
    ]
